bot:
  token: token_here
  prefix: prefix_here
  hypixel-key: needed_for_profile_command
  debug:
    enabled: false
    token: debug_token_here
    prefix: debug_prefix_here

log:
  discord-debug: false
  sql-queries: false
  
mysql:
  host: mariadb
  port: 3306
  database: tracker
  user: tracker
  password: change_me

guild-id: CHANNEL_ID
channels:
  top-players:
    - CHANNEL_ID
  top-voted:
    - CHANNEL_ID
  record: CHANNEL_ID
  total-vc: CHANNEL_ID
  zero-vc: CHANNEL_ID
  hourly-chart: CHANNEL_ID
  pie-chart: CHANNEL_ID
  admin: CHANNEL_ID
  alerts: CHANNEL_ID
  cache: CHANNEL_ID
  members-count: CHANNEL_ID
  servers-count: CHANNEL_ID
  votes-count: CHANNEL_ID
  tracks-count: CHANNEL_ID
  track-usage: CHANNEL_ID
  profile-usage: CHANNEL_ID
  skin-usage: CHANNEL_ID
roles:
  default: CHANNEL_ID