version: "3"

env_file: .env

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file: /storage/data/.env
    networks:
      - main
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - /storage/data:/etc/mysql/conf.d
    healthcheck:
      test: "cat /var/log/mysql/general-log.log | grep \"root@localhost on  using Socket\""
      interval: 1s
      retries: 120
  irmctracker_bot:
    container_name: irmctracker_bot
    build: .
    depends_on:
      - sql_database
    networks:
      - main
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
networks:
  main:

volumes:
  sql_database: