debug: false
channels:
  top:
    vc-1: 866289711050784788
    vc-2: 866289915783544832
    vc-3: 866290014274584606
    vc-4: 866594448677928960
    vc-5: 866594475110694932
    vc-6: 866594488814403615
  total-vc: 866377410102296596
  zero-vc: 866377830089621504
  text-hourly: 866288509269966878
  admin: 866594343551500308
roles:
  default: 867033463885791302
servers:
  - name: "MadCraft"
    address: "hub.madcraft.ir"
    custom-address: ""
  - name: JigsawMC
    address: hub.jigsawmc.ir
    custom-address: 
  - name: EOG
    address: eogcraft.ir
    custom-address: 
  - name: QPixel
    address: play.qpixel.ir
    custom-address: 
  - name: CastleCraft
    address: hub.castlecraft.ir
    custom-address: 
  - name: IRCraft
    address: play.ircraft.net
    custom-address: 
  - name: DarkPixel
    address: darkpixel.ir
    custom-address: 
  - name: DragonNetwork
    address: dragonnetwork.ir
    custom-address: 
  - name: MCGO
    address: play.mcgo.ir
    custom-address: 
  - name: TrexMine
    address: hub.trexmine.com
    custom-address: 
  - name: AricoGames
    address: mc.aricogames.ir
    custom-address: 
  - name: UltraNetwork
    address: mc.ultranetwork.ir
    custom-address: 
  - name: TehranGaming
    address: play.tgmc.ir
    custom-address: 
  - name: VoidPixel
    address: play.voidpixel.ir
    custom-address: 
  - name: GoldCraft
    address: mc.goldcraft.ir
    custom-address: 